# docker-compose.yml
version: '3.8'

services:
  snakeapp:
    build: .
    ports:
      - "8000:8000"
    # Optional: Set environment variables if needed
    environment:
      - RED_SNAKE_DURATION=15000  # Example duration in milliseconds
      - INVERT_CONTROLS_DURATION=10000
      - BLUE_RAT_DURATION=10000
      - NORMAL_RAT_POINTS=5
      - BLUE_RAT_POINTS=20
    # Optional: Mount volumes if needed
    volumes:
      - .:/app
    # Optional: Specify working directory
    working_dir: /app
